name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PR Reviewer Bot
        uses: omio-labs/pr-reviewer-bot@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
